[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-opensans"]

[phases.install]
cmds = ["PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm ci --omit=dev"]

[start]
cmd = "node server.js"
